version: '2.1'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack-playbook
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
    environment:
      - SERVICES=serveless,cognito,rds,sqs,sns,cloudformation
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix://var/run/docker.sock
      - HOST_TMP_FOLDER={TMPDIR}
      - LAMBDA_EXECUTOR=docker
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/root/var/run/docker.sock:/var/run/docker.sock"
